# Generated by Django 6.0 on 2025-12-15 20:16

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок статьи (макс. 200 символов)",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальная часть URL (заполняется автоматически)",
                        max_length=200,
                        unique=True,
                        verbose_name="URL-адрес",
                    ),
                ),
                ("content", models.TextField(help_text="Введите текст статьи", verbose_name="Содержимое")),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью статьи",
                        null=True,
                        upload_to="blog/previews/",
                        verbose_name="Превью (изображение)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Отметьте для публикации статьи", verbose_name="Опубликовано"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, help_text="Счетчик просмотров статьи", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
